name: Test Slack Notification

on:
  workflow_dispatch:

jobs:
  test-slack:
    runs-on: ubuntu-latest
    steps:
    - name: Test Slack Webhook
      uses: 8398a7/action-slack@v3
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        STATUS: success
        TEXT: 'Slack webhook test successful - Configuration complete!'
