name: Slack Notification

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test-slack:
    runs-on: ubuntu-latest
    steps:
    - name: Test Slack Webhook
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data '{"text": "⚙️ CI/CD Pipeline - Slack Integration Test\n✅ Slack webhook test successful\n✅ Configuration complete\n\nDetails:\n- Workflow: ${GITHUB_WORKFLOW}\n- Branch: ${GITHUB_REF}\n- Commit: ${GITHUB_SHA::7}"}' \
        ${{ secrets.SLACK_WEBHOOK_URL }}
